# Конфигурация golangci-lint для проекта
# Современная конфигурация 2025 года

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - internal/api/generated  # Игнорируем сгенерированный код

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  govet:
    check-shadowing: true
  
  golint:
    min-confidence: 0
  
  gosec:
    severity: medium
    confidence: medium
  
  gocyclo:
    min-complexity: 15
  
  maligned:
    suggest-new: true
  
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  gocognit:
    min-complexity: 15
  
  nestif:
    min-complexity: 5
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  scopelint:
    # Проверка областей видимости
    # Отключен, так как scopelint устарел, используйте exportloopref
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
  
  unconvert:
    # Проверка ненужных конвертаций типов
  
  unparam:
    # Проверка неиспользуемых параметров
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    # Основные линтеры
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Стиль кода
    - gofmt
    - goimports
    - misspell
    - unparam
    - whitespace
    
    # Производительность
    - prealloc
    - unconvert
    
    # Сложность
    - gocyclo
    - funlen
    - gocognit
    
    # Безопасность
    - gosec
    
    # Дополнительные проверки
    - exportloopref
    - gocritic
    - revive
    - stylecheck

issues:
  exclude-rules:
    # Исключаем сгенерированный код
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - funlen
    - path: internal/api/generated
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

