/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.adminservice.api;

import com.necpgame.adminservice.model.CloseSession200Response;
import com.necpgame.adminservice.model.CloseSessionRequest;
import com.necpgame.adminservice.model.CreateSession200Response;
import com.necpgame.adminservice.model.CreateSessionRequest;
import com.necpgame.adminservice.model.Error;
import com.necpgame.adminservice.model.GetActiveSessions200Response;
import org.springframework.lang.Nullable;
import com.necpgame.adminservice.model.ReconnectSession200Response;
import com.necpgame.adminservice.model.ReconnectSessionRequest;
import com.necpgame.adminservice.model.SendHeartbeat200Response;
import com.necpgame.adminservice.model.SendHeartbeatRequest;
import com.necpgame.adminservice.model.SessionState;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Session Management", description = "Управление сессиями")
public interface TechnicalApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CLOSE_SESSION = "/technical/sessions/close";
    /**
     * POST /technical/sessions/close : Закрыть сессию
     * Закрывает игровую сессию при выходе игрока. Сохраняет state персонажа. 
     *
     * @param closeSessionRequest  (required)
     * @return Сессия закрыта (status code 200)
     */
    @Operation(
        operationId = "closeSession",
        summary = "Закрыть сессию",
        description = "Закрывает игровую сессию при выходе игрока. Сохраняет state персонажа. ",
        tags = { "Session Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Сессия закрыта", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CloseSession200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_CLOSE_SESSION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CloseSession200Response> closeSession(
        @Parameter(name = "CloseSessionRequest", description = "", required = true) @Valid @RequestBody CloseSessionRequest closeSessionRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"duration\" : 0.8008281904610115, \"closed_at\" : \"2000-01-23T04:56:07.000+00:00\", \"session_id\" : \"session_id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_SESSION = "/technical/sessions/create";
    /**
     * POST /technical/sessions/create : Создать игровую сессию
     * Создает новую игровую сессию при входе игрока. Проверяет на дубликаты (concurrent sessions). 
     *
     * @param createSessionRequest  (required)
     * @return Сессия создана (status code 200)
     *         or Конфликт с текущим состоянием ресурса или ограничениями системы. Например, превышение лимитов или нарушение бизнес-правил.  (status code 409)
     */
    @Operation(
        operationId = "createSession",
        summary = "Создать игровую сессию",
        description = "Создает новую игровую сессию при входе игрока. Проверяет на дубликаты (concurrent sessions). ",
        tags = { "Session Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Сессия создана", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateSession200Response.class))
            }),
            @ApiResponse(responseCode = "409", description = "Конфликт с текущим состоянием ресурса или ограничениями системы. Например, превышение лимитов или нарушение бизнес-правил. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"LIMIT_EXCEEDED\",\"message\":\"Превышен лимит NPC для владельца\",\"details\":[{\"field\":\"maxNPCs\",\"message\":\"Достигнут максимальный лимит NPC (10)\",\"code\":\"LIMIT_EXCEEDED\"}]}}"
                    )
                })

            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_CREATE_SESSION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CreateSession200Response> createSession(
        @Parameter(name = "CreateSessionRequest", description = "", required = true) @Valid @RequestBody CreateSessionRequest createSessionRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"session_id\" : \"session_id\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"character_id\" : \"character_id\", \"afk_timeout\" : 6, \"heartbeat_interval\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ACTIVE_SESSIONS = "/technical/sessions/active";
    /**
     * GET /technical/sessions/active : Получить активные сессии
     * Возвращает список активных сессий (для админов). Может фильтроваться по account_id. 
     *
     * @param accountId  (optional)
     * @return Активные сессии (status code 200)
     */
    @Operation(
        operationId = "getActiveSessions",
        summary = "Получить активные сессии",
        description = "Возвращает список активных сессий (для админов). Может фильтроваться по account_id. ",
        tags = { "Session Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Активные сессии", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetActiveSessions200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TechnicalApi.PATH_GET_ACTIVE_SESSIONS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetActiveSessions200Response> getActiveSessions(
        @Parameter(name = "account_id", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "account_id", required = false) @Nullable String accountId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"sessions\" : [ { \"duration\" : 0.8008281904610115, \"character_name\" : \"character_name\", \"session_id\" : \"session_id\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"character_id\" : \"character_id\", \"last_heartbeat\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"duration\" : 0.8008281904610115, \"character_name\" : \"character_name\", \"session_id\" : \"session_id\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"character_id\" : \"character_id\", \"last_heartbeat\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_SESSION_STATE = "/technical/sessions/{session_id}/state";
    /**
     * GET /technical/sessions/{session_id}/state : Получить состояние сессии
     * Возвращает текущее состояние игровой сессии
     *
     * @param sessionId  (required)
     * @return Состояние сессии (status code 200)
     */
    @Operation(
        operationId = "getSessionState",
        summary = "Получить состояние сессии",
        description = "Возвращает текущее состояние игровой сессии",
        tags = { "Session Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Состояние сессии", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionState.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TechnicalApi.PATH_GET_SESSION_STATE,
        produces = { "application/json" }
    )
    default ResponseEntity<SessionState> getSessionState(
        @NotNull @Parameter(name = "session_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("session_id") String sessionId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"account_id\" : \"account_id\", \"activity\" : \"active\", \"current_activity\" : \"current_activity\", \"party_id\" : \"party_id\", \"connection_status\" : \"connected\", \"session_id\" : \"session_id\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"location\" : \"location\", \"character_id\" : \"character_id\", \"last_heartbeat\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RECONNECT_SESSION = "/technical/sessions/reconnect";
    /**
     * POST /technical/sessions/reconnect : Переподключение
     * Быстрое переподключение к существующей сессии. Восстанавливает state персонажа. 
     *
     * @param reconnectSessionRequest  (required)
     * @return Переподключение успешно (status code 200)
     */
    @Operation(
        operationId = "reconnectSession",
        summary = "Переподключение",
        description = "Быстрое переподключение к существующей сессии. Восстанавливает state персонажа. ",
        tags = { "Session Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Переподключение успешно", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ReconnectSession200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_RECONNECT_SESSION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ReconnectSession200Response> reconnectSession(
        @Parameter(name = "ReconnectSessionRequest", description = "", required = true) @Valid @RequestBody ReconnectSessionRequest reconnectSessionRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"session_id\" : \"session_id\", \"session_state\" : { \"activity\" : \"activity\", \"party_id\" : \"party_id\", \"location\" : \"location\" }, \"reconnected\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SEND_HEARTBEAT = "/technical/sessions/heartbeat";
    /**
     * POST /technical/sessions/heartbeat : Heartbeat (keepalive)
     * Отправляет heartbeat для поддержания сессии активной. Должен вызываться каждые 30 секунд. 
     *
     * @param sendHeartbeatRequest  (required)
     * @return Heartbeat принят (status code 200)
     */
    @Operation(
        operationId = "sendHeartbeat",
        summary = "Heartbeat (keepalive)",
        description = "Отправляет heartbeat для поддержания сессии активной. Должен вызываться каждые 30 секунд. ",
        tags = { "Session Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Heartbeat принят", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SendHeartbeat200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_SEND_HEARTBEAT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SendHeartbeat200Response> sendHeartbeat(
        @Parameter(name = "SendHeartbeatRequest", description = "", required = true) @Valid @RequestBody SendHeartbeatRequest sendHeartbeatRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"server_time\" : \"2000-01-23T04:56:07.000+00:00\", \"session_id\" : \"session_id\", \"last_heartbeat\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
