/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.CombatResult;
import com.necpgame.backjava.model.CombatState;
import com.necpgame.backjava.model.FleeCombat200Response;
import com.necpgame.backjava.model.FleeCombatRequest;
import com.necpgame.backjava.model.GetAvailableActions200Response;
import com.necpgame.backjava.model.InitiateCombatRequest;
import org.springframework.lang.Nullable;
import com.necpgame.backjava.model.PerformCombatActionRequest;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-06T21:22:00.452540100+03:00[Europe/Moscow]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Combat", description = "the Combat API")
public interface CombatApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_FLEE_COMBAT = "/combat/{combatId}/flee";
    /**
     * POST /combat/{combatId}/flee : РЎР±РµР¶Р°С‚СЊ РёР· Р±РѕСЏ
     *
     * @param combatId  (required)
     * @param fleeCombatRequest  (optional)
     * @return Р РµР·СѓР»СЊС‚Р°С‚ РїРѕР±РµРіР° (status code 200)
     */
    @Operation(
        operationId = "fleeCombat",
        summary = "РЎР±РµР¶Р°С‚СЊ РёР· Р±РѕСЏ",
        tags = { "Combat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Р РµР·СѓР»СЊС‚Р°С‚ РїРѕР±РµРіР°", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FleeCombat200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CombatApi.PATH_FLEE_COMBAT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<FleeCombat200Response> fleeCombat(
        @NotNull @Parameter(name = "combatId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("combatId") UUID combatId,
        @Parameter(name = "FleeCombatRequest", description = "") @Valid @RequestBody(required = false) @Nullable FleeCombatRequest fleeCombatRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true, \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_AVAILABLE_ACTIONS = "/combat/{combatId}/available-actions";
    /**
     * GET /combat/{combatId}/available-actions : Р”РѕСЃС‚СѓРїРЅС‹Рµ РґРµР№СЃС‚РІРёСЏ
     *
     * @param combatId  (required)
     * @param characterId  (required)
     * @return Р”РѕСЃС‚СѓРїРЅС‹Рµ РґРµР№СЃС‚РІРёСЏ (status code 200)
     */
    @Operation(
        operationId = "getAvailableActions",
        summary = "Р”РѕСЃС‚СѓРїРЅС‹Рµ РґРµР№СЃС‚РІРёСЏ",
        tags = { "Combat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Р”РѕСЃС‚СѓРїРЅС‹Рµ РґРµР№СЃС‚РІРёСЏ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetAvailableActions200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CombatApi.PATH_GET_AVAILABLE_ACTIONS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetAvailableActions200Response> getAvailableActions(
        @NotNull @Parameter(name = "combatId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("combatId") UUID combatId,
        @NotNull @Parameter(name = "characterId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "characterId", required = true) UUID characterId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"actions\" : [ { \"damage\" : 6, \"cost\" : 0, \"name\" : \"name\", \"available\" : true, \"description\" : \"description\", \"id\" : \"id\", \"type\" : \"attack\" }, { \"damage\" : 6, \"cost\" : 0, \"name\" : \"name\", \"available\" : true, \"description\" : \"description\", \"id\" : \"id\", \"type\" : \"attack\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_COMBAT_RESULT = "/combat/{combatId}/result";
    /**
     * GET /combat/{combatId}/result : Р РµР·СѓР»СЊС‚Р°С‚ Р±РѕСЏ
     *
     * @param combatId  (required)
     * @return Р РµР·СѓР»СЊС‚Р°С‚ Р±РѕСЏ (status code 200)
     */
    @Operation(
        operationId = "getCombatResult",
        summary = "Р РµР·СѓР»СЊС‚Р°С‚ Р±РѕСЏ",
        tags = { "Combat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Р РµР·СѓР»СЊС‚Р°С‚ Р±РѕСЏ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CombatResult.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CombatApi.PATH_GET_COMBAT_RESULT,
        produces = { "application/json" }
    )
    default ResponseEntity<CombatResult> getCombatResult(
        @NotNull @Parameter(name = "combatId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("combatId") UUID combatId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"penalties\" : \"{}\", \"victory\" : true, \"rewards\" : { \"currency\" : 6, \"experience\" : 0, \"items\" : [ \"items\", \"items\" ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_COMBAT_STATE = "/combat/{combatId}";
    /**
     * GET /combat/{combatId} : РЎРѕСЃС‚РѕСЏРЅРёРµ Р±РѕСЏ
     *
     * @param combatId  (required)
     * @return РЎРѕСЃС‚РѕСЏРЅРёРµ Р±РѕСЏ (status code 200)
     */
    @Operation(
        operationId = "getCombatState",
        summary = "РЎРѕСЃС‚РѕСЏРЅРёРµ Р±РѕСЏ",
        tags = { "Combat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "РЎРѕСЃС‚РѕСЏРЅРёРµ Р±РѕСЏ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CombatState.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CombatApi.PATH_GET_COMBAT_STATE,
        produces = { "application/json" }
    )
    default ResponseEntity<CombatState> getCombatState(
        @NotNull @Parameter(name = "combatId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("combatId") UUID combatId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentTurn\" : \"currentTurn\", \"round\" : 5, \"log\" : [ \"log\", \"log\" ], \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"active\", \"participants\" : [ { \"isAlive\" : true, \"armor\" : 5, \"name\" : \"name\", \"health\" : 0, \"maxHealth\" : 6, \"id\" : \"id\", \"type\" : \"player\", \"energy\" : 1 }, { \"isAlive\" : true, \"armor\" : 5, \"name\" : \"name\", \"health\" : 0, \"maxHealth\" : 6, \"id\" : \"id\", \"type\" : \"player\", \"energy\" : 1 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_INITIATE_COMBAT = "/combat/initiate";
    /**
     * POST /combat/initiate : РќР°С‡Р°С‚СЊ Р±РѕР№
     *
     * @param initiateCombatRequest  (optional)
     * @return Р‘РѕР№ РЅР°С‡Р°С‚ (status code 200)
     */
    @Operation(
        operationId = "initiateCombat",
        summary = "РќР°С‡Р°С‚СЊ Р±РѕР№",
        tags = { "Combat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Р‘РѕР№ РЅР°С‡Р°С‚", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CombatState.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CombatApi.PATH_INITIATE_COMBAT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CombatState> initiateCombat(
        @Parameter(name = "InitiateCombatRequest", description = "") @Valid @RequestBody(required = false) @Nullable InitiateCombatRequest initiateCombatRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentTurn\" : \"currentTurn\", \"round\" : 5, \"log\" : [ \"log\", \"log\" ], \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"active\", \"participants\" : [ { \"isAlive\" : true, \"armor\" : 5, \"name\" : \"name\", \"health\" : 0, \"maxHealth\" : 6, \"id\" : \"id\", \"type\" : \"player\", \"energy\" : 1 }, { \"isAlive\" : true, \"armor\" : 5, \"name\" : \"name\", \"health\" : 0, \"maxHealth\" : 6, \"id\" : \"id\", \"type\" : \"player\", \"energy\" : 1 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PERFORM_COMBAT_ACTION = "/combat/{combatId}/action";
    /**
     * POST /combat/{combatId}/action : Р’С‹РїРѕР»РЅРёС‚СЊ РґРµР№СЃС‚РІРёРµ РІ Р±РѕСЋ
     *
     * @param combatId  (required)
     * @param performCombatActionRequest  (optional)
     * @return Р”РµР№СЃС‚РІРёРµ РІС‹РїРѕР»РЅРµРЅРѕ (status code 200)
     */
    @Operation(
        operationId = "performCombatAction",
        summary = "Р’С‹РїРѕР»РЅРёС‚СЊ РґРµР№СЃС‚РІРёРµ РІ Р±РѕСЋ",
        tags = { "Combat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Р”РµР№СЃС‚РІРёРµ РІС‹РїРѕР»РЅРµРЅРѕ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CombatState.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CombatApi.PATH_PERFORM_COMBAT_ACTION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CombatState> performCombatAction(
        @NotNull @Parameter(name = "combatId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("combatId") UUID combatId,
        @Parameter(name = "PerformCombatActionRequest", description = "") @Valid @RequestBody(required = false) @Nullable PerformCombatActionRequest performCombatActionRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentTurn\" : \"currentTurn\", \"round\" : 5, \"log\" : [ \"log\", \"log\" ], \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"status\" : \"active\", \"participants\" : [ { \"isAlive\" : true, \"armor\" : 5, \"name\" : \"name\", \"health\" : 0, \"maxHealth\" : 6, \"id\" : \"id\", \"type\" : \"player\", \"energy\" : 1 }, { \"isAlive\" : true, \"armor\" : 5, \"name\" : \"name\", \"health\" : 0, \"maxHealth\" : 6, \"id\" : \"id\", \"type\" : \"player\", \"energy\" : 1 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
