/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.CalculateEnergyRequest;
import com.necpgame.backjava.model.CalculateLimitRequest;
import com.necpgame.backjava.model.CompatibilityCheckRequest;
import com.necpgame.backjava.model.CompatibilityResult;
import com.necpgame.backjava.model.EnergyCalculation;
import com.necpgame.backjava.model.EnergyPoolInfo;
import com.necpgame.backjava.model.EnergyRestoreResult;
import com.necpgame.backjava.model.Error;
import com.necpgame.backjava.model.ImplantLimitCalculation;
import com.necpgame.backjava.model.ImplantLimitInfo;
import com.necpgame.backjava.model.ImplantLimits;
import com.necpgame.backjava.model.ImplantSlots;
import com.necpgame.backjava.model.IndividualEnergyLimits;
import org.springframework.lang.Nullable;
import com.necpgame.backjava.model.RestoreEnergyRequest;
import java.util.UUID;
import com.necpgame.backjava.model.ValidateInstallRequest;
import com.necpgame.backjava.model.ValidationResult;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-06T19:51:47.912860600+03:00[Europe/Moscow]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Combat", description = "the Combat API")
public interface GameplayImplantsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CALCULATE_ENERGY_CONSUMPTION = "/gameplay/combat/implants/{player_id}/energy/calculate";
    /**
     * POST /gameplay/combat/implants/{player_id}/energy/calculate : Рассчитать энергетическое потребление имплантов
     * Рассчитывает энергетическое потребление имплантов и проверяет, можно ли установить импланты с учетом энергетического лимита. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Энергетический лимит 
     *
     * @param playerId Идентификатор игрока (required)
     * @param calculateEnergyRequest  (required)
     * @return Расчет энергетического потребления (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "calculateEnergyConsumption",
        summary = "Рассчитать энергетическое потребление имплантов",
        description = "Рассчитывает энергетическое потребление имплантов и проверяет, можно ли установить импланты с учетом энергетического лимита. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Энергетический лимит ",
        tags = { "Combat", "Implants", "Energy" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Расчет энергетического потребления", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EnergyCalculation.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GameplayImplantsApi.PATH_CALCULATE_ENERGY_CONSUMPTION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EnergyCalculation> calculateEnergyConsumption(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId,
        @Parameter(name = "CalculateEnergyRequest", description = "", required = true) @Valid @RequestBody CalculateEnergyRequest calculateEnergyRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"can_install\" : true, \"warnings\" : [ { \"message\" : \"message\", \"type\" : \"compatibility\" }, { \"message\" : \"message\", \"type\" : \"compatibility\" } ], \"total_drain\" : 0.08008282, \"individual_limits\" : [ { \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"usage\" : 0.14658129, \"limit\" : 0.6027456, \"can_exceed\" : true }, { \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"usage\" : 0.14658129, \"limit\" : 0.6027456, \"can_exceed\" : true } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CALCULATE_IMPLANT_LIMIT = "/gameplay/combat/implants/{player_id}/limit/calculate";
    /**
     * POST /gameplay/combat/implants/{player_id}/limit/calculate : Рассчитать лимит имплантов с учетом всех факторов
     * Рассчитывает лимит имплантов с учетом базового лимита, бонусов от класса/прокачки и штрафов от человечности. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Лимит имплантов 
     *
     * @param playerId Идентификатор игрока (required)
     * @param calculateLimitRequest  (required)
     * @return Расчет лимита имплантов (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "calculateImplantLimit",
        summary = "Рассчитать лимит имплантов с учетом всех факторов",
        description = "Рассчитывает лимит имплантов с учетом базового лимита, бонусов от класса/прокачки и штрафов от человечности. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Лимит имплантов ",
        tags = { "Combat", "Implants", "Limits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Расчет лимита имплантов", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ImplantLimitCalculation.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GameplayImplantsApi.PATH_CALCULATE_IMPLANT_LIMIT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ImplantLimitCalculation> calculateImplantLimit(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId,
        @Parameter(name = "CalculateLimitRequest", description = "", required = true) @Valid @RequestBody CalculateLimitRequest calculateLimitRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"total\" : 0, \"penalties\" : { \"humanity\" : 0, \"quality\" : 0 }, \"breakdown\" : \"breakdown\", \"bonuses\" : { \"progression\" : 0, \"class\" : 0 }, \"base\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CHECK_COMPATIBILITY = "/gameplay/combat/implants/{player_id}/compatibility";
    /**
     * POST /gameplay/combat/implants/{player_id}/compatibility : Проверить совместимость импланта с установленными
     * Проверяет совместимость импланта с уже установленными имплантами игрока. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Совместимость 
     *
     * @param playerId Идентификатор игрока (required)
     * @param compatibilityCheckRequest  (required)
     * @return Результат проверки совместимости (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "checkCompatibility",
        summary = "Проверить совместимость импланта с установленными",
        description = "Проверяет совместимость импланта с уже установленными имплантами игрока. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Совместимость ",
        tags = { "Combat", "Implants", "Compatibility" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Результат проверки совместимости", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CompatibilityResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GameplayImplantsApi.PATH_CHECK_COMPATIBILITY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CompatibilityResult> checkCompatibility(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId,
        @Parameter(name = "CompatibilityCheckRequest", description = "", required = true) @Valid @RequestBody CompatibilityCheckRequest compatibilityCheckRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"warnings\" : [ { \"message\" : \"message\", \"type\" : \"compatibility\" }, { \"message\" : \"message\", \"type\" : \"compatibility\" } ], \"is_compatible\" : true, \"conflicts\" : [ { \"severity\" : \"low\", \"reason\" : \"reason\", \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"severity\" : \"low\", \"reason\" : \"reason\", \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ENERGY_POOL = "/gameplay/combat/implants/{player_id}/energy";
    /**
     * GET /gameplay/combat/implants/{player_id}/energy : Получить информацию об энергетическом пуле
     * Получает информацию об энергетическом пуле игрока, включая общий пул, использованную и доступную энергию, скорость восстановления. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Энергетический лимит 
     *
     * @param playerId Идентификатор игрока (required)
     * @return Информация об энергетическом пуле (status code 200)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "getEnergyPool",
        summary = "Получить информацию об энергетическом пуле",
        description = "Получает информацию об энергетическом пуле игрока, включая общий пул, использованную и доступную энергию, скорость восстановления. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Энергетический лимит ",
        tags = { "Combat", "Implants", "Energy" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Информация об энергетическом пуле", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EnergyPoolInfo.class))
            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GameplayImplantsApi.PATH_GET_ENERGY_POOL,
        produces = { "application/json" }
    )
    default ResponseEntity<EnergyPoolInfo> getEnergyPool(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"total_pool\" : 0.08008282, \"regen_rate\" : 0.5962134, \"max_level\" : 0.23021358, \"current_level\" : 0.5637377, \"available\" : 0.14658129, \"used\" : 0.6027456, \"individual_limits\" : [ { \"individual_limit\" : 0.7061401, \"penalty_on_exceed\" : { \"key\" : \"\" }, \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"current_usage\" : 0.9301444, \"can_exceed\" : true }, { \"individual_limit\" : 0.7061401, \"penalty_on_exceed\" : { \"key\" : \"\" }, \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"current_usage\" : 0.9301444, \"can_exceed\" : true } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_IMPLANT_LIMIT = "/gameplay/combat/implants/{player_id}/limit";
    /**
     * GET /gameplay/combat/implants/{player_id}/limit : Получить текущий лимит имплантов
     * Получает текущий лимит имплантов игрока с детализацией бонусов и штрафов.
     *
     * @param playerId Идентификатор игрока (required)
     * @return Информация о лимите имплантов (status code 200)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "getImplantLimit",
        summary = "Получить текущий лимит имплантов",
        description = "Получает текущий лимит имплантов игрока с детализацией бонусов и штрафов.",
        tags = { "Combat", "Implants", "Limits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Информация о лимите имплантов", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ImplantLimitInfo.class))
            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GameplayImplantsApi.PATH_GET_IMPLANT_LIMIT,
        produces = { "application/json" }
    )
    default ResponseEntity<ImplantLimitInfo> getImplantLimit(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"humanity_penalty\" : 0, \"available\" : 0, \"base_limit\" : 0, \"used\" : 0, \"bonuses\" : { \"other\" : 0, \"progression\" : 0, \"class\" : 0 }, \"can_exceed_temporarily\" : true, \"current_limit\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_IMPLANT_LIMITS = "/gameplay/combat/implants/{player_id}/limits";
    /**
     * GET /gameplay/combat/implants/{player_id}/limits : Получить лимиты имплантов игрока
     * Получает информацию о лимитах имплантов игрока, включая базовый лимит, бонусы от класса и прокачки, штрафы от человечности, и текущее использование. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Лимит имплантов 
     *
     * @param playerId Идентификатор игрока (required)
     * @return Информация о лимитах имплантов (status code 200)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "getImplantLimits",
        summary = "Получить лимиты имплантов игрока",
        description = "Получает информацию о лимитах имплантов игрока, включая базовый лимит, бонусы от класса и прокачки, штрафы от человечности, и текущее использование. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Лимит имплантов ",
        tags = { "Combat", "Implants", "Limits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Информация о лимитах имплантов", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ImplantLimits.class))
            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GameplayImplantsApi.PATH_GET_IMPLANT_LIMITS,
        produces = { "application/json" }
    )
    default ResponseEntity<ImplantLimits> getImplantLimits(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"bonus_from_progression\" : 0, \"temporary_exceed_duration\" : 0.9301444, \"humanity_penalty\" : 0, \"available_slots\" : 0, \"base_limit\" : 0, \"used_slots\" : 0, \"can_exceed_temporarily\" : true, \"current_limit\" : 0, \"bonus_from_class\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_IMPLANT_SLOTS = "/gameplay/combat/implants/{player_id}/slots";
    /**
     * GET /gameplay/combat/implants/{player_id}/slots : Получить доступные слоты имплантов игрока
     * Возвращает информацию о доступных слотах имплантов игрока по типам. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Ограничения имплантов 
     *
     * @param playerId Идентификатор игрока (required)
     * @param type Тип импланта (опционально, для фильтрации) (optional)
     * @return Информация о слотах имплантов (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "getImplantSlots",
        summary = "Получить доступные слоты имплантов игрока",
        description = "Возвращает информацию о доступных слотах имплантов игрока по типам. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Ограничения имплантов ",
        tags = { "Combat", "Implants", "Limits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Информация о слотах имплантов", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ImplantSlots.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GameplayImplantsApi.PATH_GET_IMPLANT_SLOTS,
        produces = { "application/json" }
    )
    default ResponseEntity<ImplantSlots> getImplantSlots(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId,
        @Parameter(name = "type", description = "Тип импланта (опционально, для фильтрации)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "type", required = false) @Nullable String type
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"slots_by_type\" : { \"mobility\" : [ { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"os\" : [ { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"defensive\" : [ { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"combat\" : [ { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ], \"tactical\" : [ { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"is_occupied\" : true, \"slot_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"can_install\" : true, \"installed_implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_INDIVIDUAL_ENERGY_LIMITS = "/gameplay/combat/implants/{player_id}/energy/limits";
    /**
     * GET /gameplay/combat/implants/{player_id}/energy/limits : Получить индивидуальные энергетические ограничения имплантов
     * Получает индивидуальные энергетические ограничения для каждого установленного импланта. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Энергетический лимит 
     *
     * @param playerId Идентификатор игрока (required)
     * @return Индивидуальные энергетические ограничения (status code 200)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "getIndividualEnergyLimits",
        summary = "Получить индивидуальные энергетические ограничения имплантов",
        description = "Получает индивидуальные энергетические ограничения для каждого установленного импланта. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Энергетический лимит ",
        tags = { "Combat", "Implants", "Energy" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Индивидуальные энергетические ограничения", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = IndividualEnergyLimits.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GameplayImplantsApi.PATH_GET_INDIVIDUAL_ENERGY_LIMITS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<IndividualEnergyLimits>> getIndividualEnergyLimits(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"individual_limit\" : 0.7061401, \"penalty_on_exceed\" : { \"key\" : \"\" }, \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"current_usage\" : 0.9301444, \"can_exceed\" : true }, { \"individual_limit\" : 0.7061401, \"penalty_on_exceed\" : { \"key\" : \"\" }, \"implant_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"current_usage\" : 0.9301444, \"can_exceed\" : true } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RESTORE_ENERGY = "/gameplay/combat/implants/{player_id}/energy/restore";
    /**
     * POST /gameplay/combat/implants/{player_id}/energy/restore : Восстановить энергию
     * Восстанавливает энергию игрока (если есть механизм восстановления).
     *
     * @param playerId Идентификатор игрока (required)
     * @param restoreEnergyRequest  (required)
     * @return Результат восстановления энергии (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Запрос синтаксически корректен, но семантически неверен. Например, некорректное состояние ресурса для операции.  (status code 422)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "restoreEnergy",
        summary = "Восстановить энергию",
        description = "Восстанавливает энергию игрока (если есть механизм восстановления).",
        tags = { "Combat", "Implants", "Energy" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Результат восстановления энергии", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EnergyRestoreResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "422", description = "Запрос синтаксически корректен, но семантически неверен. Например, некорректное состояние ресурса для операции. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INVALID_STATE\",\"message\":\"Операция невозможна в текущем состоянии ресурса\",\"details\":[{\"field\":\"status\",\"message\":\"Нельзя отменить выполненный сценарий\",\"code\":\"INVALID_STATE\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GameplayImplantsApi.PATH_RESTORE_ENERGY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EnergyRestoreResult> restoreEnergy(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId,
        @Parameter(name = "RestoreEnergyRequest", description = "", required = true) @Valid @RequestBody RestoreEnergyRequest restoreEnergyRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"new_level\" : 0.08008282, \"cooldown\" : 0.14658129, \"restored_amount\" : 0.6027456 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_VALIDATE_INSTALL = "/gameplay/combat/implants/{player_id}/validate-install";
    /**
     * POST /gameplay/combat/implants/{player_id}/validate-install : Валидировать возможность установки импланта
     * Валидирует возможность установки импланта с проверкой всех ограничений: слоты, совместимость, лимит имплантов, энергетический лимит. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -&gt; Ограничения имплантов 
     *
     * @param playerId Идентификатор игрока (required)
     * @param validateInstallRequest  (required)
     * @return Результат валидации установки (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     *         or Пользователь не аутентифицирован. Требуется валидный токен доступа.  (status code 401)
     *         or Запрошенный ресурс не найден.  (status code 404)
     *         or Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса.  (status code 500)
     */
    @Operation(
        operationId = "validateInstall",
        summary = "Валидировать возможность установки импланта",
        description = "Валидирует возможность установки импланта с проверкой всех ограничений: слоты, совместимость, лимит имплантов, энергетический лимит. Источник: .BRAIN/02-gameplay/combat/combat-implants-limits.md -> Ограничения имплантов ",
        tags = { "Combat", "Implants", "Validation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Результат валидации установки", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Пользователь не аутентифицирован. Требуется валидный токен доступа. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"Требуется аутентификация\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервера. Непредвиденная ошибка при обработке запроса. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Произошла внутренняя ошибка сервера\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GameplayImplantsApi.PATH_VALIDATE_INSTALL,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ValidationResult> validateInstall(
        @NotNull @Parameter(name = "player_id", description = "Идентификатор игрока", required = true, in = ParameterIn.PATH) @PathVariable("player_id") UUID playerId,
        @Parameter(name = "ValidateInstallRequest", description = "", required = true) @Valid @RequestBody ValidateInstallRequest validateInstallRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"energy_ok\" : true, \"reasons\" : [ { \"severity\" : \"low\", \"message\" : \"message\", \"type\" : \"slot\" }, { \"severity\" : \"low\", \"message\" : \"message\", \"type\" : \"slot\" } ], \"can_install\" : true, \"warnings\" : [ { \"message\" : \"message\", \"type\" : \"compatibility\" }, { \"message\" : \"message\", \"type\" : \"compatibility\" } ], \"slot_available\" : true, \"limit_ok\" : true, \"errors\" : [ { \"code\" : \"code\", \"message\" : \"message\" }, { \"code\" : \"code\", \"message\" : \"message\" } ], \"compatibility_ok\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
