/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.DropItem200Response;
import com.necpgame.backjava.model.EquipItem200Response;
import com.necpgame.backjava.model.EquipRequest;
import com.necpgame.backjava.model.Error;
import com.necpgame.backjava.model.GetEquipment200Response;
import com.necpgame.backjava.model.InventoryResponse;
import com.necpgame.backjava.model.ItemCategory;
import org.springframework.lang.Nullable;
import java.util.UUID;
import com.necpgame.backjava.model.UnequipItem200Response;
import com.necpgame.backjava.model.UnequipItemRequest;
import com.necpgame.backjava.model.UseItem200Response;
import com.necpgame.backjava.model.UseItemRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-06T20:50:45.778329200+03:00[Europe/Moscow]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Inventory", description = "the Inventory API")
public interface InventoryApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DROP_ITEM = "/inventory/drop";
    /**
     * DELETE /inventory/drop : Р’С‹Р±СЂРѕСЃРёС‚СЊ РїСЂРµРґРјРµС‚
     * РЈРґР°Р»СЏРµС‚ РїСЂРµРґРјРµС‚ РёР· РёРЅРІРµРЅС‚Р°СЂСЏ РїРµСЂСЃРѕРЅР°Р¶Р° (РІС‹Р±СЂР°СЃС‹РІР°РµС‚).  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РїСЂРµРґРјРµС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ РїСЂРµРґРјРµС‚ РЅРµ СЌРєРёРїРёСЂРѕРІР°РЅ - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ РїСЂРµРґРјРµС‚ РЅРµ РєРІРµСЃС‚РѕРІС‹Р№ (РЅРµР»СЊР·СЏ РІС‹Р±СЂРѕСЃРёС‚СЊ) - РЈРґР°Р»СЏРµС‚ РїСЂРµРґРјРµС‚ (РёР»Рё СѓРјРµРЅСЊС€Р°РµС‚ РєРѕР»РёС‡РµСЃС‚РІРѕ, РµСЃР»Рё stackable)  **РСЃС‚РѕС‡РЅРёРє:** &#x60;.BRAIN/05-technical/ui-main-game.md&#x60; (Р Р°Р·РґРµР» 3.1) 
     *
     * @param characterId ID РїРµСЂСЃРѕРЅР°Р¶Р° (required)
     * @param itemId ID РїСЂРµРґРјРµС‚Р° РґР»СЏ РІС‹Р±СЂР°СЃС‹РІР°РЅРёСЏ (required)
     * @param quantity РљРѕР»РёС‡РµСЃС‚РІРѕ РїСЂРµРґРјРµС‚РѕРІ РґР»СЏ РІС‹Р±СЂР°СЃС‹РІР°РЅРёСЏ (РґР»СЏ stackable) (optional, default to 1)
     * @return РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ РІС‹Р±СЂРѕС€РµРЅ (status code 200)
     *         or РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ.  (status code 400)
     *         or РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ.  (status code 403)
     *         or Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ.  (status code 404)
     *         or РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°.  (status code 401)
     */
    @Operation(
        operationId = "dropItem",
        summary = "Р’С‹Р±СЂРѕСЃРёС‚СЊ РїСЂРµРґРјРµС‚",
        description = "РЈРґР°Р»СЏРµС‚ РїСЂРµРґРјРµС‚ РёР· РёРЅРІРµРЅС‚Р°СЂСЏ РїРµСЂСЃРѕРЅР°Р¶Р° (РІС‹Р±СЂР°СЃС‹РІР°РµС‚).  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РїСЂРµРґРјРµС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ РїСЂРµРґРјРµС‚ РЅРµ СЌРєРёРїРёСЂРѕРІР°РЅ - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ РїСЂРµРґРјРµС‚ РЅРµ РєРІРµСЃС‚РѕРІС‹Р№ (РЅРµР»СЊР·СЏ РІС‹Р±СЂРѕСЃРёС‚СЊ) - РЈРґР°Р»СЏРµС‚ РїСЂРµРґРјРµС‚ (РёР»Рё СѓРјРµРЅСЊС€Р°РµС‚ РєРѕР»РёС‡РµСЃС‚РІРѕ, РµСЃР»Рё stackable)  **РСЃС‚РѕС‡РЅРёРє:** `.BRAIN/05-technical/ui-main-game.md` (Р Р°Р·РґРµР» 3.1) ",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ РІС‹Р±СЂРѕС€РµРЅ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DropItem200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\",\"details\":[{\"field\":\"name\",\"message\":\"РРјСЏ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РЅРµ РїСѓСЃС‚С‹Рј\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"FORBIDDEN\",\"message\":\"РќРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РѕРїРµСЂР°С†РёРё\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ\",\"details\":[{\"field\":\"id\",\"message\":\"NPC СЃ СѓРєР°Р·Р°РЅРЅС‹Рј ID РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"РўСЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = InventoryApi.PATH_DROP_ITEM,
        produces = { "application/json" }
    )
    default ResponseEntity<DropItem200Response> dropItem(
        @NotNull @Parameter(name = "characterId", description = "ID РїРµСЂСЃРѕРЅР°Р¶Р°", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "characterId", required = true) UUID characterId,
        @NotNull @Parameter(name = "itemId", description = "ID РїСЂРµРґРјРµС‚Р° РґР»СЏ РІС‹Р±СЂР°СЃС‹РІР°РЅРёСЏ", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "itemId", required = true) String itemId,
        @Min(value = 1) @Parameter(name = "quantity", description = "РљРѕР»РёС‡РµСЃС‚РІРѕ РїСЂРµРґРјРµС‚РѕРІ РґР»СЏ РІС‹Р±СЂР°СЃС‹РІР°РЅРёСЏ (РґР»СЏ stackable)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "quantity", required = false, defaultValue = "1") Integer quantity
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true, \"message\" : \"РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ РІС‹Р±СЂРѕС€РµРЅ\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EQUIP_ITEM = "/inventory/equip";
    /**
     * POST /inventory/equip : Р­РєРёРїРёСЂРѕРІР°С‚СЊ РїСЂРµРґРјРµС‚
     * Р­РєРёРїРёСЂСѓРµС‚ РїСЂРµРґРјРµС‚ РёР· РёРЅРІРµРЅС‚Р°СЂСЏ РІ СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓСЋС‰РёР№ СЃР»РѕС‚ СЌРєРёРїРёСЂРѕРІРєРё.  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РїСЂРµРґРјРµС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ - РџСЂРѕРІРµСЂСЏРµС‚ С‚СЂРµР±РѕРІР°РЅРёСЏ РґР»СЏ СЌРєРёРїРёСЂРѕРІРєРё (СѓСЂРѕРІРµРЅСЊ, С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРєРё) - Р•СЃР»Рё СЃР»РѕС‚ Р·Р°РЅСЏС‚ - Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё СЃРЅРёРјР°РµС‚ С‚РµРєСѓС‰РёР№ РїСЂРµРґРјРµС‚ - РџСЂРёРјРµРЅСЏРµС‚ Р±РѕРЅСѓСЃС‹ РѕС‚ РЅРѕРІРѕРіРѕ РїСЂРµРґРјРµС‚Р°  **РСЃС‚РѕС‡РЅРёРє:** &#x60;.BRAIN/05-technical/ui-main-game.md&#x60; (Р Р°Р·РґРµР» 3.1) 
     *
     * @param equipRequest  (required)
     * @return РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ СЌРєРёРїРёСЂРѕРІР°РЅ (status code 200)
     *         or РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ.  (status code 400)
     *         or РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ.  (status code 403)
     *         or Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ.  (status code 404)
     *         or РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°.  (status code 401)
     */
    @Operation(
        operationId = "equipItem",
        summary = "Р­РєРёРїРёСЂРѕРІР°С‚СЊ РїСЂРµРґРјРµС‚",
        description = "Р­РєРёРїРёСЂСѓРµС‚ РїСЂРµРґРјРµС‚ РёР· РёРЅРІРµРЅС‚Р°СЂСЏ РІ СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓСЋС‰РёР№ СЃР»РѕС‚ СЌРєРёРїРёСЂРѕРІРєРё.  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РїСЂРµРґРјРµС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ - РџСЂРѕРІРµСЂСЏРµС‚ С‚СЂРµР±РѕРІР°РЅРёСЏ РґР»СЏ СЌРєРёРїРёСЂРѕРІРєРё (СѓСЂРѕРІРµРЅСЊ, С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРєРё) - Р•СЃР»Рё СЃР»РѕС‚ Р·Р°РЅСЏС‚ - Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё СЃРЅРёРјР°РµС‚ С‚РµРєСѓС‰РёР№ РїСЂРµРґРјРµС‚ - РџСЂРёРјРµРЅСЏРµС‚ Р±РѕРЅСѓСЃС‹ РѕС‚ РЅРѕРІРѕРіРѕ РїСЂРµРґРјРµС‚Р°  **РСЃС‚РѕС‡РЅРёРє:** `.BRAIN/05-technical/ui-main-game.md` (Р Р°Р·РґРµР» 3.1) ",
        tags = { "Inventory", "Equipment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ СЌРєРёРїРёСЂРѕРІР°РЅ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EquipItem200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\",\"details\":[{\"field\":\"name\",\"message\":\"РРјСЏ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РЅРµ РїСѓСЃС‚С‹Рј\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"FORBIDDEN\",\"message\":\"РќРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РѕРїРµСЂР°С†РёРё\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ\",\"details\":[{\"field\":\"id\",\"message\":\"NPC СЃ СѓРєР°Р·Р°РЅРЅС‹Рј ID РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"РўСЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = InventoryApi.PATH_EQUIP_ITEM,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EquipItem200Response> equipItem(
        @Parameter(name = "EquipRequest", description = "", required = true) @Valid @RequestBody EquipRequest equipRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true, \"equipment\" : { \"slotName\" : \"РћСЃРЅРѕРІРЅРѕРµ РѕСЂСѓР¶РёРµ\", \"item\" : { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" }, \"slotType\" : \"weapon_primary\", \"isEmpty\" : false, \"bonuses\" : { \"damage\" : 25, \"accuracy\" : 10 } }, \"unequippedItem\" : { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" }, \"message\" : \"РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ СЌРєРёРїРёСЂРѕРІР°РЅ\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_EQUIPMENT = "/inventory/equipment";
    /**
     * GET /inventory/equipment : РџРѕР»СѓС‡РёС‚СЊ СЌРєРёРїРёСЂРѕРІРєСѓ РїРµСЂСЃРѕРЅР°Р¶Р°
     * Р’РѕР·РІСЂР°С‰Р°РµС‚ С‚РµРєСѓС‰СѓСЋ СЌРєРёРїРёСЂРѕРІРєСѓ РїРµСЂСЃРѕРЅР°Р¶Р° (РІСЃРµ СЃР»РѕС‚С‹ СЃ РїСЂРµРґРјРµС‚Р°РјРё).  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - Р’РѕР·РІСЂР°С‰Р°РµС‚ РІСЃРµ СЃР»РѕС‚С‹ СЌРєРёРїРёСЂРѕРІРєРё - РџРѕРєР°Р·С‹РІР°РµС‚ РєР°РєРёРµ СЃР»РѕС‚С‹ Р·Р°РЅСЏС‚С‹ Рё РєР°РєРёРµ СЃРІРѕР±РѕРґРЅС‹ - Р’РѕР·РІСЂР°С‰Р°РµС‚ Р±РѕРЅСѓСЃС‹ РѕС‚ СЌРєРёРїРёСЂРѕРІР°РЅРЅС‹С… РїСЂРµРґРјРµС‚РѕРІ  **РСЃС‚РѕС‡РЅРёРє:** &#x60;.BRAIN/05-technical/ui-main-game.md&#x60; (Р Р°Р·РґРµР» 3.1) 
     *
     * @param characterId ID РїРµСЂСЃРѕРЅР°Р¶Р° (required)
     * @return Р­РєРёРїРёСЂРѕРІРєР° РїРµСЂСЃРѕРЅР°Р¶Р° (status code 200)
     *         or Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ.  (status code 404)
     *         or РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°.  (status code 401)
     */
    @Operation(
        operationId = "getEquipment",
        summary = "РџРѕР»СѓС‡РёС‚СЊ СЌРєРёРїРёСЂРѕРІРєСѓ РїРµСЂСЃРѕРЅР°Р¶Р°",
        description = "Р’РѕР·РІСЂР°С‰Р°РµС‚ С‚РµРєСѓС‰СѓСЋ СЌРєРёРїРёСЂРѕРІРєСѓ РїРµСЂСЃРѕРЅР°Р¶Р° (РІСЃРµ СЃР»РѕС‚С‹ СЃ РїСЂРµРґРјРµС‚Р°РјРё).  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - Р’РѕР·РІСЂР°С‰Р°РµС‚ РІСЃРµ СЃР»РѕС‚С‹ СЌРєРёРїРёСЂРѕРІРєРё - РџРѕРєР°Р·С‹РІР°РµС‚ РєР°РєРёРµ СЃР»РѕС‚С‹ Р·Р°РЅСЏС‚С‹ Рё РєР°РєРёРµ СЃРІРѕР±РѕРґРЅС‹ - Р’РѕР·РІСЂР°С‰Р°РµС‚ Р±РѕРЅСѓСЃС‹ РѕС‚ СЌРєРёРїРёСЂРѕРІР°РЅРЅС‹С… РїСЂРµРґРјРµС‚РѕРІ  **РСЃС‚РѕС‡РЅРёРє:** `.BRAIN/05-technical/ui-main-game.md` (Р Р°Р·РґРµР» 3.1) ",
        tags = { "Inventory", "Equipment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Р­РєРёРїРёСЂРѕРІРєР° РїРµСЂСЃРѕРЅР°Р¶Р°", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetEquipment200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ\",\"details\":[{\"field\":\"id\",\"message\":\"NPC СЃ СѓРєР°Р·Р°РЅРЅС‹Рј ID РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"РўСЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = InventoryApi.PATH_GET_EQUIPMENT,
        produces = { "application/json" }
    )
    default ResponseEntity<GetEquipment200Response> getEquipment(
        @NotNull @Parameter(name = "characterId", description = "ID РїРµСЂСЃРѕРЅР°Р¶Р°", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "characterId", required = true) UUID characterId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"slots\" : [ { \"slotName\" : \"РћСЃРЅРѕРІРЅРѕРµ РѕСЂСѓР¶РёРµ\", \"item\" : { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" }, \"slotType\" : \"weapon_primary\", \"isEmpty\" : false, \"bonuses\" : { \"damage\" : 25, \"accuracy\" : 10 } }, { \"slotName\" : \"РћСЃРЅРѕРІРЅРѕРµ РѕСЂСѓР¶РёРµ\", \"item\" : { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" }, \"slotType\" : \"weapon_primary\", \"isEmpty\" : false, \"bonuses\" : { \"damage\" : 25, \"accuracy\" : 10 } } ], \"totalBonuses\" : { \"health\" : 50, \"armor\" : 25, \"damage\" : 15 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_INVENTORY = "/inventory";
    /**
     * GET /inventory : РџРѕР»СѓС‡РёС‚СЊ РёРЅРІРµРЅС‚Р°СЂСЊ РїРµСЂСЃРѕРЅР°Р¶Р°
     * Р’РѕР·РІСЂР°С‰Р°РµС‚ РёРЅРІРµРЅС‚Р°СЂСЊ РїРµСЂСЃРѕРЅР°Р¶Р° СЃРѕ РІСЃРµРјРё РїСЂРµРґРјРµС‚Р°РјРё, РІРµСЃРѕРј Рё Р»РёРјРёС‚РѕРј.  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - Р’РѕР·РІСЂР°С‰Р°РµС‚ РІСЃРµ РїСЂРµРґРјРµС‚С‹ РІ РёРЅРІРµРЅС‚Р°СЂРµ - Р“СЂСѓРїРїРёСЂСѓРµС‚ РїСЂРµРґРјРµС‚С‹ РїРѕ РєР°С‚РµРіРѕСЂРёСЏРј - РЎРєР»Р°РґС‹РІР°РµС‚ stackable РїСЂРµРґРјРµС‚С‹ - РџРѕРєР°Р·С‹РІР°РµС‚ С‚РµРєСѓС‰РёР№ РІРµСЃ Рё Р»РёРјРёС‚  **РСЃС‚РѕС‡РЅРёРє:** &#x60;.BRAIN/05-technical/ui-main-game.md&#x60; (Р Р°Р·РґРµР» 3.1) 
     *
     * @param characterId ID РїРµСЂСЃРѕРЅР°Р¶Р° (required)
     * @param category Р¤РёР»СЊС‚СЂ РїРѕ РєР°С‚РµРіРѕСЂРёРё РїСЂРµРґРјРµС‚РѕРІ (optional)
     * @return РРЅРІРµРЅС‚Р°СЂСЊ РїРµСЂСЃРѕРЅР°Р¶Р° (status code 200)
     *         or Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ.  (status code 404)
     *         or РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°.  (status code 401)
     */
    @Operation(
        operationId = "getInventory",
        summary = "РџРѕР»СѓС‡РёС‚СЊ РёРЅРІРµРЅС‚Р°СЂСЊ РїРµСЂСЃРѕРЅР°Р¶Р°",
        description = "Р’РѕР·РІСЂР°С‰Р°РµС‚ РёРЅРІРµРЅС‚Р°СЂСЊ РїРµСЂСЃРѕРЅР°Р¶Р° СЃРѕ РІСЃРµРјРё РїСЂРµРґРјРµС‚Р°РјРё, РІРµСЃРѕРј Рё Р»РёРјРёС‚РѕРј.  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - Р’РѕР·РІСЂР°С‰Р°РµС‚ РІСЃРµ РїСЂРµРґРјРµС‚С‹ РІ РёРЅРІРµРЅС‚Р°СЂРµ - Р“СЂСѓРїРїРёСЂСѓРµС‚ РїСЂРµРґРјРµС‚С‹ РїРѕ РєР°С‚РµРіРѕСЂРёСЏРј - РЎРєР»Р°РґС‹РІР°РµС‚ stackable РїСЂРµРґРјРµС‚С‹ - РџРѕРєР°Р·С‹РІР°РµС‚ С‚РµРєСѓС‰РёР№ РІРµСЃ Рё Р»РёРјРёС‚  **РСЃС‚РѕС‡РЅРёРє:** `.BRAIN/05-technical/ui-main-game.md` (Р Р°Р·РґРµР» 3.1) ",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "РРЅРІРµРЅС‚Р°СЂСЊ РїРµСЂСЃРѕРЅР°Р¶Р°", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InventoryResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ\",\"details\":[{\"field\":\"id\",\"message\":\"NPC СЃ СѓРєР°Р·Р°РЅРЅС‹Рј ID РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"РўСЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = InventoryApi.PATH_GET_INVENTORY,
        produces = { "application/json" }
    )
    default ResponseEntity<InventoryResponse> getInventory(
        @NotNull @Parameter(name = "characterId", description = "ID РїРµСЂСЃРѕРЅР°Р¶Р°", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "characterId", required = true) UUID characterId,
        @Parameter(name = "category", description = "Р¤РёР»СЊС‚СЂ РїРѕ РєР°С‚РµРіРѕСЂРёРё РїСЂРµРґРјРµС‚РѕРІ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "category", required = false) @Nullable ItemCategory category
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"currentWeight\" : 45.5, \"maxWeight\" : 100.0, \"categories\" : { \"weapons\" : 3, \"armor\" : 5, \"consumables\" : 10 }, \"items\" : [ { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" }, { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UNEQUIP_ITEM = "/inventory/unequip";
    /**
     * POST /inventory/unequip : РЎРЅСЏС‚СЊ СЌРєРёРїРёСЂРѕРІР°РЅРЅС‹Р№ РїСЂРµРґРјРµС‚
     * РЎРЅРёРјР°РµС‚ РїСЂРµРґРјРµС‚ РёР· СЃР»РѕС‚Р° СЌРєРёРїРёСЂРѕРІРєРё Рё РїРѕРјРµС‰Р°РµС‚ РІ РёРЅРІРµРЅС‚Р°СЂСЊ.  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ СЃР»РѕС‚ Р·Р°РЅСЏС‚ - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РјРµСЃС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ (РІРµСЃ) - РЎРЅРёРјР°РµС‚ Р±РѕРЅСѓСЃС‹ РѕС‚ РїСЂРµРґРјРµС‚Р° - РџРѕРјРµС‰Р°РµС‚ РїСЂРµРґРјРµС‚ РІ РёРЅРІРµРЅС‚Р°СЂСЊ  **РСЃС‚РѕС‡РЅРёРє:** &#x60;.BRAIN/05-technical/ui-main-game.md&#x60; (Р Р°Р·РґРµР» 3.1) 
     *
     * @param unequipItemRequest  (required)
     * @return РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ СЃРЅСЏС‚ (status code 200)
     *         or РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ.  (status code 400)
     *         or РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ.  (status code 403)
     *         or Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ.  (status code 404)
     *         or РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°.  (status code 401)
     */
    @Operation(
        operationId = "unequipItem",
        summary = "РЎРЅСЏС‚СЊ СЌРєРёРїРёСЂРѕРІР°РЅРЅС‹Р№ РїСЂРµРґРјРµС‚",
        description = "РЎРЅРёРјР°РµС‚ РїСЂРµРґРјРµС‚ РёР· СЃР»РѕС‚Р° СЌРєРёРїРёСЂРѕРІРєРё Рё РїРѕРјРµС‰Р°РµС‚ РІ РёРЅРІРµРЅС‚Р°СЂСЊ.  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ СЃР»РѕС‚ Р·Р°РЅСЏС‚ - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РјРµСЃС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ (РІРµСЃ) - РЎРЅРёРјР°РµС‚ Р±РѕРЅСѓСЃС‹ РѕС‚ РїСЂРµРґРјРµС‚Р° - РџРѕРјРµС‰Р°РµС‚ РїСЂРµРґРјРµС‚ РІ РёРЅРІРµРЅС‚Р°СЂСЊ  **РСЃС‚РѕС‡РЅРёРє:** `.BRAIN/05-technical/ui-main-game.md` (Р Р°Р·РґРµР» 3.1) ",
        tags = { "Inventory", "Equipment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ СЃРЅСЏС‚", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UnequipItem200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\",\"details\":[{\"field\":\"name\",\"message\":\"РРјСЏ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РЅРµ РїСѓСЃС‚С‹Рј\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"FORBIDDEN\",\"message\":\"РќРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РѕРїРµСЂР°С†РёРё\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ\",\"details\":[{\"field\":\"id\",\"message\":\"NPC СЃ СѓРєР°Р·Р°РЅРЅС‹Рј ID РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"РўСЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = InventoryApi.PATH_UNEQUIP_ITEM,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<UnequipItem200Response> unequipItem(
        @Parameter(name = "UnequipItemRequest", description = "", required = true) @Valid @RequestBody UnequipItemRequest unequipItemRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"item\" : { \"stackable\" : false, \"requirements\" : { \"minLevel\" : 0, \"minDexterity\" : 1, \"minStrength\" : 6, \"minIntelligence\" : 5 }, \"quantity\" : 1, \"questItem\" : false, \"equippable\" : true, \"description\" : \"РЎС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРёСЃС‚РѕР»РµС‚ РєР°Р»РёР±СЂР° 10РјРј\", \"weight\" : 1.5, \"usable\" : false, \"name\" : \"M-10AF Lexington\", \"id\" : \"item_pistol_01\", \"category\" : \"weapons\", \"value\" : 500, \"rarity\" : \"common\" }, \"success\" : true, \"message\" : \"РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ СЃРЅСЏС‚\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_USE_ITEM = "/inventory/use";
    /**
     * POST /inventory/use : РСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РїСЂРµРґРјРµС‚
     * РСЃРїРѕР»СЊР·СѓРµС‚ РїСЂРµРґРјРµС‚ РёР· РёРЅРІРµРЅС‚Р°СЂСЏ (РјРµРґРёРєР°РјРµРЅС‚С‹, СЂР°СЃС…РѕРґРЅРёРєРё).  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РїСЂРµРґРјРµС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ РїСЂРµРґРјРµС‚ РјРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ - РџСЂРёРјРµРЅСЏРµС‚ СЌС„С„РµРєС‚С‹ РѕС‚ РїСЂРµРґРјРµС‚Р° - РЈРјРµРЅСЊС€Р°РµС‚ РєРѕР»РёС‡РµСЃС‚РІРѕ РЅР° 1 (РёР»Рё СѓРґР°Р»СЏРµС‚, РµСЃР»Рё Р±С‹Р» РїРѕСЃР»РµРґРЅРёР№)  **РСЃС‚РѕС‡РЅРёРє:** &#x60;.BRAIN/05-technical/ui-main-game.md&#x60; (Р Р°Р·РґРµР» 3.1) 
     *
     * @param useItemRequest  (required)
     * @return РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°РЅ (status code 200)
     *         or РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ.  (status code 400)
     *         or РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ.  (status code 403)
     *         or Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ.  (status code 404)
     *         or РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°.  (status code 401)
     */
    @Operation(
        operationId = "useItem",
        summary = "РСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РїСЂРµРґРјРµС‚",
        description = "РСЃРїРѕР»СЊР·СѓРµС‚ РїСЂРµРґРјРµС‚ РёР· РёРЅРІРµРЅС‚Р°СЂСЏ (РјРµРґРёРєР°РјРµРЅС‚С‹, СЂР°СЃС…РѕРґРЅРёРєРё).  **Р‘РёР·РЅРµСЃ-Р»РѕРіРёРєР°:** - РџСЂРѕРІРµСЂСЏРµС‚ РЅР°Р»РёС‡РёРµ РїСЂРµРґРјРµС‚Р° РІ РёРЅРІРµРЅС‚Р°СЂРµ - РџСЂРѕРІРµСЂСЏРµС‚, С‡С‚Рѕ РїСЂРµРґРјРµС‚ РјРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ - РџСЂРёРјРµРЅСЏРµС‚ СЌС„С„РµРєС‚С‹ РѕС‚ РїСЂРµРґРјРµС‚Р° - РЈРјРµРЅСЊС€Р°РµС‚ РєРѕР»РёС‡РµСЃС‚РІРѕ РЅР° 1 (РёР»Рё СѓРґР°Р»СЏРµС‚, РµСЃР»Рё Р±С‹Р» РїРѕСЃР»РµРґРЅРёР№)  **РСЃС‚РѕС‡РЅРёРє:** `.BRAIN/05-technical/ui-main-game.md` (Р Р°Р·РґРµР» 3.1) ",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°РЅ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UseItem200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "РќРµРІРµСЂРЅС‹Р№ Р·Р°РїСЂРѕСЃ. РџР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР° РЅРµРєРѕСЂСЂРµРєС‚РЅС‹ РёР»Рё РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚ РѕР±СЏР·Р°С‚РµР»СЊРЅС‹Рµ РїРѕР»СЏ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\",\"details\":[{\"field\":\"name\",\"message\":\"РРјСЏ РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РЅРµ РїСѓСЃС‚С‹Рј\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "РЈ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РЅРµС‚ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РґР°РЅРЅРѕР№ РѕРїРµСЂР°С†РёРё. РђСѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ РїСЂРѕС€Р»Р° СѓСЃРїРµС€РЅРѕ, РЅРѕ РґРѕСЃС‚СѓРїР° РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"FORBIDDEN\",\"message\":\"РќРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РїСЂР°РІ РґР»СЏ РІС‹РїРѕР»РЅРµРЅРёСЏ РѕРїРµСЂР°С†РёРё\",\"details\":[]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Р—Р°РїСЂРѕС€РµРЅРЅС‹Р№ СЂРµСЃСѓСЂСЃ РЅРµ РЅР°Р№РґРµРЅ\",\"details\":[{\"field\":\"id\",\"message\":\"NPC СЃ СѓРєР°Р·Р°РЅРЅС‹Рј ID РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ РЅРµ Р°СѓС‚РµРЅС‚РёС„РёС†РёСЂРѕРІР°РЅ. РўСЂРµР±СѓРµС‚СЃСЏ РІР°Р»РёРґРЅС‹Р№ С‚РѕРєРµРЅ РґРѕСЃС‚СѓРїР°. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"UNAUTHORIZED\",\"message\":\"РўСЂРµР±СѓРµС‚СЃСЏ Р°СѓС‚РµРЅС‚РёС„РёРєР°С†РёСЏ\",\"details\":[]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = InventoryApi.PATH_USE_ITEM,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<UseItem200Response> useItem(
        @Parameter(name = "UseItemRequest", description = "", required = true) @Valid @RequestBody UseItemRequest useItemRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"effects\" : [ { \"type\" : \"heal\", \"value\" : 50, \"description\" : \"Р’РѕСЃСЃС‚Р°РЅРѕРІР»РµРЅРѕ 50 HP\" } ], \"success\" : true, \"message\" : \"РџСЂРµРґРјРµС‚ СѓСЃРїРµС€РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°РЅ\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"РќРµРІРµСЂРЅС‹Рµ РїР°СЂР°РјРµС‚СЂС‹ Р·Р°РїСЂРѕСЃР°\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}

