/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.ClaimAttachmentsRequest;
import com.necpgame.backjava.model.GetInbox200Response;
import org.springframework.lang.Nullable;
import com.necpgame.backjava.model.SendMail200Response;
import com.necpgame.backjava.model.SendMailRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Mail", description = "Почтовая система")
public interface MailApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CLAIM_ATTACHMENTS = "/mail/{mail_id}/claim-attachments";
    /**
     * POST /mail/{mail_id}/claim-attachments : Забрать вложения
     * Забирает items/gold из письма. Требует оплату COD (если установлен). 
     *
     * @param mailId  (required)
     * @param claimAttachmentsRequest  (optional)
     * @return Вложения получены (status code 200)
     */
    @Operation(
        operationId = "claimAttachments",
        summary = "Забрать вложения",
        description = "Забирает items/gold из письма. Требует оплату COD (если установлен). ",
        tags = { "Mail" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Вложения получены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MailApi.PATH_CLAIM_ATTACHMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> claimAttachments(
        @NotNull @Parameter(name = "mail_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mail_id") String mailId,
        @Parameter(name = "ClaimAttachmentsRequest", description = "") @Valid @RequestBody(required = false) @Nullable ClaimAttachmentsRequest claimAttachmentsRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_MAIL = "/mail/{mail_id}/delete";
    /**
     * DELETE /mail/{mail_id}/delete : Удалить письмо
     * Удаляет письмо из inbox
     *
     * @param mailId  (required)
     * @return Письмо удалено (status code 200)
     */
    @Operation(
        operationId = "deleteMail",
        summary = "Удалить письмо",
        description = "Удаляет письмо из inbox",
        tags = { "Mail" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Письмо удалено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = MailApi.PATH_DELETE_MAIL,
        produces = { "application/json" }
    )
    default ResponseEntity<Object> deleteMail(
        @NotNull @Parameter(name = "mail_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mail_id") String mailId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_INBOX = "/mail/inbox";
    /**
     * GET /mail/inbox : Получить входящие письма
     * Возвращает список писем в inbox. Поддерживает пагинацию и фильтрацию. 
     *
     * @param characterId  (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 50)
     * @param unreadOnly  (optional, default to false)
     * @return Список писем (status code 200)
     */
    @Operation(
        operationId = "getInbox",
        summary = "Получить входящие письма",
        description = "Возвращает список писем в inbox. Поддерживает пагинацию и фильтрацию. ",
        tags = { "Mail" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список писем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetInbox200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MailApi.PATH_GET_INBOX,
        produces = { "application/json" }
    )
    default ResponseEntity<GetInbox200Response> getInbox(
        @NotNull @Parameter(name = "character_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "character_id", required = true) String characterId,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "50") Integer limit,
        @Parameter(name = "unread_only", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "unread_only", required = false, defaultValue = "false") Boolean unreadOnly
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"pagination\" : { \"total\" : 156, \"has_next\" : true, \"page\" : 1, \"total_pages\" : 8, \"has_prev\" : false, \"page_size\" : 20 }, \"mail\" : [ { \"is_read\" : true, \"is_system\" : true, \"has_attachments\" : true, \"expires_at\" : \"2000-01-23T04:56:07.000+00:00\", \"mail_id\" : \"mail_id\", \"subject\" : \"subject\", \"gold_attached\" : 0.8008281904610115, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"sender_name\" : \"sender_name\", \"body\" : \"body\", \"cod_amount\" : 6.027456183070403 }, { \"is_read\" : true, \"is_system\" : true, \"has_attachments\" : true, \"expires_at\" : \"2000-01-23T04:56:07.000+00:00\", \"mail_id\" : \"mail_id\", \"subject\" : \"subject\", \"gold_attached\" : 0.8008281904610115, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"sender_name\" : \"sender_name\", \"body\" : \"body\", \"cod_amount\" : 6.027456183070403 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_READ_MAIL = "/mail/{mail_id}/read";
    /**
     * POST /mail/{mail_id}/read : Прочитать письмо
     * Отмечает письмо как прочитанное
     *
     * @param mailId  (required)
     * @return Письмо прочитано (status code 200)
     */
    @Operation(
        operationId = "readMail",
        summary = "Прочитать письмо",
        description = "Отмечает письмо как прочитанное",
        tags = { "Mail" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Письмо прочитано", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MailApi.PATH_READ_MAIL,
        produces = { "application/json" }
    )
    default ResponseEntity<Object> readMail(
        @NotNull @Parameter(name = "mail_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mail_id") String mailId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SEND_MAIL = "/mail/send";
    /**
     * POST /mail/send : Отправить письмо
     * Отправляет письмо другому игроку. Можно приложить items (до 10) и gold. Можно установить COD (оплата при получении). 
     *
     * @param sendMailRequest  (required)
     * @return Письмо отправлено (status code 200)
     */
    @Operation(
        operationId = "sendMail",
        summary = "Отправить письмо",
        description = "Отправляет письмо другому игроку. Можно приложить items (до 10) и gold. Можно установить COD (оплата при получении). ",
        tags = { "Mail" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Письмо отправлено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SendMail200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MailApi.PATH_SEND_MAIL,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SendMail200Response> sendMail(
        @Parameter(name = "SendMailRequest", description = "", required = true) @Valid @RequestBody SendMailRequest sendMailRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"mail_id\" : \"mail_id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
