/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.ContentOverview;
import com.necpgame.backjava.model.ContentStatus;
import com.necpgame.backjava.model.GetMVPEndpoints200Response;
import com.necpgame.backjava.model.GetMVPHealth200Response;
import com.necpgame.backjava.model.GetMVPModels200Response;
import com.necpgame.backjava.model.InitialGameData;
import com.necpgame.backjava.model.MainGameUIData;
import org.springframework.lang.Nullable;
import com.necpgame.backjava.model.TextVersionState;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-08T02:15:59.618208300+03:00[Europe/Moscow]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Content Overview", description = "Обзор контента")
public interface MvpApi {

    String PATH_GET_CONTENT_OVERVIEW = "/mvp/content/overview";
    /**
     * GET /mvp/content/overview : Получить обзор контента
     *
     * @param period  (optional)
     * @return Обзор контента (status code 200)
     */
    @Operation(
        operationId = "getContentOverview",
        summary = "Получить обзор контента",
        tags = { "Content Overview" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Обзор контента", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ContentOverview.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_CONTENT_OVERVIEW,
        produces = { "application/json" }
    )
    ResponseEntity<ContentOverview> getContentOverview(
        @Parameter(name = "period", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "period", required = false) @Nullable String period
    );


    String PATH_GET_CONTENT_STATUS = "/mvp/content/status";
    /**
     * GET /mvp/content/status : Получить статус готовности контента
     *
     * @return Статус контента (status code 200)
     */
    @Operation(
        operationId = "getContentStatus",
        summary = "Получить статус готовности контента",
        tags = { "Content Overview" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Статус контента", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ContentStatus.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_CONTENT_STATUS,
        produces = { "application/json" }
    )
    ResponseEntity<ContentStatus> getContentStatus(
        
    );


    String PATH_GET_INITIAL_DATA = "/mvp/initial-data";
    /**
     * GET /mvp/initial-data : Получить начальные данные игры
     * Данные для первого запуска игры
     *
     * @return Начальные данные (status code 200)
     */
    @Operation(
        operationId = "getInitialData",
        summary = "Получить начальные данные игры",
        description = "Данные для первого запуска игры",
        tags = { "Initial Data" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Начальные данные", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InitialGameData.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_INITIAL_DATA,
        produces = { "application/json" }
    )
    ResponseEntity<InitialGameData> getInitialData(
        
    );


    String PATH_GET_MVP_ENDPOINTS = "/mvp/endpoints";
    /**
     * GET /mvp/endpoints : Получить список MVP endpoints
     *
     * @return MVP endpoints (status code 200)
     */
    @Operation(
        operationId = "getMVPEndpoints",
        summary = "Получить список MVP endpoints",
        tags = { "MVP" },
        responses = {
            @ApiResponse(responseCode = "200", description = "MVP endpoints", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetMVPEndpoints200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_MVP_ENDPOINTS,
        produces = { "application/json" }
    )
    ResponseEntity<GetMVPEndpoints200Response> getMVPEndpoints(
        
    );


    String PATH_GET_MVP_HEALTH = "/mvp/health";
    /**
     * GET /mvp/health : Проверка здоровья MVP систем
     *
     * @return Статус MVP систем (status code 200)
     */
    @Operation(
        operationId = "getMVPHealth",
        summary = "Проверка здоровья MVP систем",
        tags = { "MVP" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Статус MVP систем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetMVPHealth200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_MVP_HEALTH,
        produces = { "application/json" }
    )
    ResponseEntity<GetMVPHealth200Response> getMVPHealth(
        
    );


    String PATH_GET_MVP_MODELS = "/mvp/models";
    /**
     * GET /mvp/models : Получить data models для MVP
     *
     * @return Data models (status code 200)
     */
    @Operation(
        operationId = "getMVPModels",
        summary = "Получить data models для MVP",
        tags = { "MVP" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Data models", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetMVPModels200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_MVP_MODELS,
        produces = { "application/json" }
    )
    ResponseEntity<GetMVPModels200Response> getMVPModels(
        
    );


    String PATH_GET_MAIN_GAME_UI = "/mvp/ui/main-game";
    /**
     * GET /mvp/ui/main-game : Получить данные для основного UI
     *
     * @param characterId  (required)
     * @return Данные для UI (status code 200)
     */
    @Operation(
        operationId = "getMainGameUI",
        summary = "Получить данные для основного UI",
        tags = { "MVP" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Данные для UI", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MainGameUIData.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_MAIN_GAME_UI,
        produces = { "application/json" }
    )
    ResponseEntity<MainGameUIData> getMainGameUI(
        @NotNull @Parameter(name = "character_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "character_id", required = true) UUID characterId
    );


    String PATH_GET_TEXT_VERSION_STATE = "/mvp/text-version/state";
    /**
     * GET /mvp/text-version/state : Получить состояние игры для текстовой версии
     * Упрощенное состояние для текстового frontend
     *
     * @param characterId  (required)
     * @return Состояние для текстовой версии (status code 200)
     */
    @Operation(
        operationId = "getTextVersionState",
        summary = "Получить состояние игры для текстовой версии",
        description = "Упрощенное состояние для текстового frontend",
        tags = { "MVP" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Состояние для текстовой версии", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TextVersionState.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MvpApi.PATH_GET_TEXT_VERSION_STATE,
        produces = { "application/json" }
    )
    ResponseEntity<TextVersionState> getTextVersionState(
        @NotNull @Parameter(name = "character_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "character_id", required = true) UUID characterId
    );

}
