/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.CompleteQuestRequest;
import com.necpgame.backjava.model.DialogueChoiceRequest;
import com.necpgame.backjava.model.DialogueChoiceResult;
import com.necpgame.backjava.model.DialogueNode;
import com.necpgame.backjava.model.Error;
import com.necpgame.backjava.model.GetActiveQuests200Response;
import com.necpgame.backjava.model.QuestCompletionResult;
import com.necpgame.backjava.model.QuestInstance;
import com.necpgame.backjava.model.SkillCheckRequest;
import com.necpgame.backjava.model.SkillCheckResult;
import com.necpgame.backjava.model.StartQuestRequest;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Quest Execution", description = "Выполнение квестов")
public interface NarrativeApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ABANDON_QUEST = "/narrative/quest-engine/instances/{instance_id}/abandon";
    /**
     * POST /narrative/quest-engine/instances/{instance_id}/abandon : Отказаться от квеста
     *
     * @param instanceId  (required)
     * @return Квест заброшен (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     */
    @Operation(
        operationId = "abandonQuest",
        summary = "Отказаться от квеста",
        tags = { "Quest Execution" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Квест заброшен"),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NarrativeApi.PATH_ABANDON_QUEST,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> abandonQuest(
        @NotNull @Parameter(name = "instance_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("instance_id") UUID instanceId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CHOOSE_DIALOGUE_OPTION = "/narrative/quest-engine/instances/{instance_id}/dialogue/choose";
    /**
     * POST /narrative/quest-engine/instances/{instance_id}/dialogue/choose : Выбрать вариант диалога
     *
     * @param instanceId  (required)
     * @param dialogueChoiceRequest  (required)
     * @return Результат выбора (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     */
    @Operation(
        operationId = "chooseDialogueOption",
        summary = "Выбрать вариант диалога",
        tags = { "Dialogue" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Результат выбора", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DialogueChoiceResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NarrativeApi.PATH_CHOOSE_DIALOGUE_OPTION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<DialogueChoiceResult> chooseDialogueOption(
        @NotNull @Parameter(name = "instance_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("instance_id") UUID instanceId,
        @Parameter(name = "DialogueChoiceRequest", description = "", required = true) @Valid @RequestBody DialogueChoiceRequest dialogueChoiceRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"next_node\" : { \"speaker\" : \"Jackie Welles\", \"options\" : [ { \"effects\" : { \"key\" : \"\" }, \"leads_to_node\" : \"leads_to_node\", \"required_attribute\" : { \"min_value\" : 12, \"attribute\" : \"INTELLIGENCE\" }, \"option_id\" : \"option_id\", \"skill_check\" : { \"difficulty\" : 15, \"advantage\" : true, \"skill\" : \"PERSUASION\" }, \"text\" : \"[Corpo] I'm always ready for business.\" }, { \"effects\" : { \"key\" : \"\" }, \"leads_to_node\" : \"leads_to_node\", \"required_attribute\" : { \"min_value\" : 12, \"attribute\" : \"INTELLIGENCE\" }, \"option_id\" : \"option_id\", \"skill_check\" : { \"difficulty\" : 15, \"advantage\" : true, \"skill\" : \"PERSUASION\" }, \"text\" : \"[Corpo] I'm always ready for business.\" } ], \"text\" : \"Yo, V! Ready for your first gig?\", \"conditions\" : { \"key\" : \"\" }, \"node_id\" : \"node_id\" }, \"success\" : true, \"effects_applied\" : { \"key\" : \"\" }, \"quest_updated\" : true, \"skill_check_performed\" : { \"difficulty\" : 0, \"advantage_used\" : true, \"total\" : 19, \"success\" : true, \"skill\" : \"skill\", \"modifier\" : 5, \"roll\" : 14, \"critical_success\" : true, \"critical_failure\" : true, \"rolls\" : [ 6, 6 ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_COMPLETE_QUEST = "/narrative/quest-engine/instances/{instance_id}/complete";
    /**
     * POST /narrative/quest-engine/instances/{instance_id}/complete : Завершить квест
     *
     * @param instanceId  (required)
     * @param completeQuestRequest  (required)
     * @return Квест завершен (status code 200)
     */
    @Operation(
        operationId = "completeQuest",
        summary = "Завершить квест",
        tags = { "Quest Execution" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Квест завершен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = QuestCompletionResult.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NarrativeApi.PATH_COMPLETE_QUEST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<QuestCompletionResult> completeQuest(
        @NotNull @Parameter(name = "instance_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("instance_id") UUID instanceId,
        @Parameter(name = "CompleteQuestRequest", description = "", required = true) @Valid @RequestBody CompleteQuestRequest completeQuestRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"reputation_changes\" : { \"ARASAKA\" : -10, \"NOMADS\" : 25 }, \"completion_time\" : \"2000-01-23T04:56:07.000+00:00\", \"unlocked_quests\" : [ \"unlocked_quests\", \"unlocked_quests\" ], \"quest_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"rewards\" : { \"reputation\" : { \"key\" : 6 }, \"currency\" : { \"eddies\" : 10000 }, \"experience\" : 5000, \"items\" : [ { \"quantity\" : 0, \"item_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"quantity\" : 0, \"item_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ACTIVE_QUESTS = "/narrative/quest-engine/character/{character_id}/active";
    /**
     * GET /narrative/quest-engine/character/{character_id}/active : Получить активные квесты персонажа
     *
     * @param characterId  (required)
     * @return Активные квесты (status code 200)
     */
    @Operation(
        operationId = "getActiveQuests",
        summary = "Получить активные квесты персонажа",
        tags = { "Quest State" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Активные квесты", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetActiveQuests200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NarrativeApi.PATH_GET_ACTIVE_QUESTS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetActiveQuests200Response> getActiveQuests(
        @NotNull @Parameter(name = "character_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("character_id") UUID characterId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"max_active_quests\" : 20, \"active_quests\" : [ { \"completed_at\" : \"2000-01-23T04:56:07.000+00:00\", \"current_branch_id\" : \"current_branch_id\", \"current_dialogue_node_id\" : \"current_dialogue_node_id\", \"flags\" : { \"key\" : \"\" }, \"progress\" : { \"key\" : { \"current\" : 0, \"completed\" : true, \"target\" : 6 } }, \"started_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"character_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"quest_name\" : \"First Contact\", \"quest_template_id\" : \"quest_template_id\", \"status\" : \"ACTIVE\" }, { \"completed_at\" : \"2000-01-23T04:56:07.000+00:00\", \"current_branch_id\" : \"current_branch_id\", \"current_dialogue_node_id\" : \"current_dialogue_node_id\", \"flags\" : { \"key\" : \"\" }, \"progress\" : { \"key\" : { \"current\" : 0, \"completed\" : true, \"target\" : 6 } }, \"started_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"character_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"quest_name\" : \"First Contact\", \"quest_template_id\" : \"quest_template_id\", \"status\" : \"ACTIVE\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_CURRENT_DIALOGUE = "/narrative/quest-engine/instances/{instance_id}/dialogue";
    /**
     * GET /narrative/quest-engine/instances/{instance_id}/dialogue : Получить текущий диалог
     *
     * @param instanceId  (required)
     * @return Текущий диалог (status code 200)
     *         or Запрошенный ресурс не найден.  (status code 404)
     */
    @Operation(
        operationId = "getCurrentDialogue",
        summary = "Получить текущий диалог",
        tags = { "Dialogue" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Текущий диалог", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DialogueNode.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NarrativeApi.PATH_GET_CURRENT_DIALOGUE,
        produces = { "application/json" }
    )
    default ResponseEntity<DialogueNode> getCurrentDialogue(
        @NotNull @Parameter(name = "instance_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("instance_id") UUID instanceId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"speaker\" : \"Jackie Welles\", \"options\" : [ { \"effects\" : { \"key\" : \"\" }, \"leads_to_node\" : \"leads_to_node\", \"required_attribute\" : { \"min_value\" : 12, \"attribute\" : \"INTELLIGENCE\" }, \"option_id\" : \"option_id\", \"skill_check\" : { \"difficulty\" : 15, \"advantage\" : true, \"skill\" : \"PERSUASION\" }, \"text\" : \"[Corpo] I'm always ready for business.\" }, { \"effects\" : { \"key\" : \"\" }, \"leads_to_node\" : \"leads_to_node\", \"required_attribute\" : { \"min_value\" : 12, \"attribute\" : \"INTELLIGENCE\" }, \"option_id\" : \"option_id\", \"skill_check\" : { \"difficulty\" : 15, \"advantage\" : true, \"skill\" : \"PERSUASION\" }, \"text\" : \"[Corpo] I'm always ready for business.\" } ], \"text\" : \"Yo, V! Ready for your first gig?\", \"conditions\" : { \"key\" : \"\" }, \"node_id\" : \"node_id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_QUEST_INSTANCE = "/narrative/quest-engine/instances/{instance_id}";
    /**
     * GET /narrative/quest-engine/instances/{instance_id} : Получить состояние квеста
     *
     * @param instanceId  (required)
     * @return Состояние квеста (status code 200)
     *         or Запрошенный ресурс не найден.  (status code 404)
     */
    @Operation(
        operationId = "getQuestInstance",
        summary = "Получить состояние квеста",
        tags = { "Quest State" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Состояние квеста", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = QuestInstance.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрошенный ресурс не найден. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"Запрошенный ресурс не найден\",\"details\":[{\"field\":\"id\",\"message\":\"NPC с указанным ID не существует\",\"code\":\"RESOURCE_NOT_FOUND\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NarrativeApi.PATH_GET_QUEST_INSTANCE,
        produces = { "application/json" }
    )
    default ResponseEntity<QuestInstance> getQuestInstance(
        @NotNull @Parameter(name = "instance_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("instance_id") UUID instanceId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"completed_at\" : \"2000-01-23T04:56:07.000+00:00\", \"current_branch_id\" : \"current_branch_id\", \"current_dialogue_node_id\" : \"current_dialogue_node_id\", \"flags\" : { \"key\" : \"\" }, \"progress\" : { \"key\" : { \"current\" : 0, \"completed\" : true, \"target\" : 6 } }, \"started_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"character_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"quest_name\" : \"First Contact\", \"quest_template_id\" : \"quest_template_id\", \"status\" : \"ACTIVE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PERFORM_SKILL_CHECK = "/narrative/quest-engine/instances/{instance_id}/skill-check";
    /**
     * POST /narrative/quest-engine/instances/{instance_id}/skill-check : Выполнить skill check
     * D&amp;D skill check (бросок d20 + модификатор)
     *
     * @param instanceId  (required)
     * @param skillCheckRequest  (required)
     * @return Результат проверки (status code 200)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     */
    @Operation(
        operationId = "performSkillCheck",
        summary = "Выполнить skill check",
        description = "D&D skill check (бросок d20 + модификатор)",
        tags = { "Quest Execution" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Результат проверки", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SkillCheckResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NarrativeApi.PATH_PERFORM_SKILL_CHECK,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SkillCheckResult> performSkillCheck(
        @NotNull @Parameter(name = "instance_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("instance_id") UUID instanceId,
        @Parameter(name = "SkillCheckRequest", description = "", required = true) @Valid @RequestBody SkillCheckRequest skillCheckRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"difficulty\" : 0, \"advantage_used\" : true, \"total\" : 19, \"success\" : true, \"skill\" : \"skill\", \"modifier\" : 5, \"roll\" : 14, \"critical_success\" : true, \"critical_failure\" : true, \"rolls\" : [ 6, 6 ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_START_QUEST = "/narrative/quest-engine/start";
    /**
     * POST /narrative/quest-engine/start : Начать новый квест
     *
     * @param startQuestRequest  (required)
     * @return Квест начат (status code 201)
     *         or Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля.  (status code 400)
     */
    @Operation(
        operationId = "startQuest",
        summary = "Начать новый квест",
        tags = { "Quest Execution" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Квест начат", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = QuestInstance.class))
            }),
            @ApiResponse(responseCode = "400", description = "Неверный запрос. Параметры запроса некорректны или отсутствуют обязательные поля. ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"error\":{\"code\":\"VALIDATION_ERROR\",\"message\":\"Неверные параметры запроса\",\"details\":[{\"field\":\"name\",\"message\":\"Имя должно быть не пустым\",\"code\":\"REQUIRED\"}]}}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NarrativeApi.PATH_START_QUEST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<QuestInstance> startQuest(
        @Parameter(name = "StartQuestRequest", description = "", required = true) @Valid @RequestBody StartQuestRequest startQuestRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"completed_at\" : \"2000-01-23T04:56:07.000+00:00\", \"current_branch_id\" : \"current_branch_id\", \"current_dialogue_node_id\" : \"current_dialogue_node_id\", \"flags\" : { \"key\" : \"\" }, \"progress\" : { \"key\" : { \"current\" : 0, \"completed\" : true, \"target\" : 6 } }, \"started_at\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"character_id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"quest_name\" : \"First Contact\", \"quest_template_id\" : \"quest_template_id\", \"status\" : \"ACTIVE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"code\" : \"VALIDATION_ERROR\", \"details\" : [ { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" }, { \"code\" : \"code\", \"field\" : \"field\", \"message\" : \"message\" } ], \"message\" : \"Неверные параметры запроса\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
