/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.BlockPlayerRequest;
import com.necpgame.backjava.model.CreatePartyRequest;
import com.necpgame.backjava.model.GetFriends200Response;
import com.necpgame.backjava.model.InviteToPartyRequest;
import com.necpgame.backjava.model.JoinPartyRequest;
import com.necpgame.backjava.model.Party;
import com.necpgame.backjava.model.PartyDetails;
import com.necpgame.backjava.model.SendFriendRequestRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Friends", description = "Система друзей")
@Tag(name = "Party", description = "Система групп")
public interface SocialApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_ACCEPT_FRIEND_REQUEST = "/social/friends/request/{request_id}/accept";
    @Operation(
        operationId = "acceptFriendRequest",
        summary = "Принять запрос в друзья",
        description = "Принимает запрос, добавляет в friends list",
        tags = { "Friends" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос принят", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_ACCEPT_FRIEND_REQUEST,
        produces = { "application/json" }
    )
    default ResponseEntity<Object> acceptFriendRequest(
        @NotNull @Parameter(name = "request_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("request_id") String requestId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_BLOCK_PLAYER = "/social/friends/block";
    @Operation(
        operationId = "blockPlayer",
        summary = "Заблокировать игрока",
        description = "Добавляет игрока в block list. Блокирует сообщения, invites, trade. ",
        tags = { "Friends" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Игрок заблокирован", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_BLOCK_PLAYER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> blockPlayer(
        @Parameter(name = "BlockPlayerRequest", description = "", required = true) @Valid @RequestBody BlockPlayerRequest blockPlayerRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_GET_FRIENDS = "/social/friends";
    @Operation(
        operationId = "getFriends",
        summary = "Получить список друзей",
        description = "Возвращает список друзей с online статусом",
        tags = { "Friends" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список друзей", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetFriends200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SocialApi.PATH_GET_FRIENDS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetFriends200Response> getFriends(
        @NotNull @Parameter(name = "player_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "player_id", required = true) String playerId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_REMOVE_FRIEND = "/social/friends/{friend_id}/remove";
    @Operation(
        operationId = "removeFriend",
        summary = "Удалить из друзей",
        description = "Удаляет игрока из списка друзей",
        tags = { "Friends" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Удален из друзей", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SocialApi.PATH_REMOVE_FRIEND,
        produces = { "application/json" }
    )
    default ResponseEntity<Object> removeFriend(
        @NotNull @Parameter(name = "friend_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("friend_id") String friendId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_SEND_FRIEND_REQUEST = "/social/friends/request";
    @Operation(
        operationId = "sendFriendRequest",
        summary = "Отправить запрос в друзья",
        description = "Отправляет запрос на добавление в друзья",
        tags = { "Friends" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Запрос отправлен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_SEND_FRIEND_REQUEST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> sendFriendRequest(
        @Parameter(name = "SendFriendRequestRequest", description = "", required = true) @Valid @RequestBody SendFriendRequestRequest sendFriendRequestRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_CREATE_PARTY = "/social/party/create";
    @Operation(
        operationId = "createParty",
        summary = "Создать группу",
        description = "Создает новую группу. Создатель становится лидером. ",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Группа создана", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Party.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_CREATE_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Party> createParty(
        @Parameter(name = "CreatePartyRequest", description = "", required = true) @Valid @RequestBody CreatePartyRequest createPartyRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"party_id\" : \"party_id\", \"members\" : [ \"members\", \"members\" ], \"max_members\" : 0, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"leader_id\" : \"leader_id\", \"loot_mode\" : \"loot_mode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_GET_PARTY = "/social/party/{party_id}";
    @Operation(
        operationId = "getParty",
        summary = "Получить информацию о группе",
        description = "Возвращает детали группы, участников, настройки",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Информация о группе", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PartyDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SocialApi.PATH_GET_PARTY,
        produces = { "application/json" }
    )
    default ResponseEntity<PartyDetails> getParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"member_details\" : [ { \"level\" : 6, \"name\" : \"name\", \"character_id\" : \"character_id\", \"is_online\" : true, \"class\" : \"class\" }, { \"level\" : 6, \"name\" : \"name\", \"character_id\" : \"character_id\", \"is_online\" : true, \"class\" : \"class\" } ], \"party_id\" : \"party_id\", \"members\" : [ \"members\", \"members\" ], \"max_members\" : 0, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"leader_id\" : \"leader_id\", \"loot_mode\" : \"loot_mode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_INVITE_TO_PARTY = "/social/party/{party_id}/invite";
    @Operation(
        operationId = "inviteToParty",
        summary = "Пригласить в группу",
        description = "Отправляет приглашение в группу. Только лидер может приглашать. ",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Приглашение отправлено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_INVITE_TO_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> inviteToParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId,
        @Parameter(name = "InviteToPartyRequest", description = "", required = true) @Valid @RequestBody InviteToPartyRequest inviteToPartyRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_JOIN_PARTY = "/social/party/{party_id}/join";
    @Operation(
        operationId = "joinParty",
        summary = "Присоединиться к группе",
        description = "Принимает приглашение и присоединяется к группе",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Присоединился к группе", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Party.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_JOIN_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Party> joinParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId,
        @Parameter(name = "JoinPartyRequest", description = "", required = true) @Valid @RequestBody JoinPartyRequest joinPartyRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"party_id\" : \"party_id\", \"members\" : [ \"members\", \"members\" ], \"max_members\" : 0, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"leader_id\" : \"leader_id\", \"loot_mode\" : \"loot_mode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    String PATH_LEAVE_PARTY = "/social/party/{party_id}/leave";
    @Operation(
        operationId = "leaveParty",
        summary = "Покинуть группу",
        description = "Покидает группу. Если лидер - лидерство передается другому. ",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Покинул группу", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_LEAVE_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> leaveParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId,
        @Parameter(name = "JoinPartyRequest", description = "", required = true) @Valid @RequestBody JoinPartyRequest joinPartyRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
