/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.CreatePartyRequest;
import com.necpgame.backjava.model.InviteToPartyRequest;
import com.necpgame.backjava.model.JoinPartyRequest;
import com.necpgame.backjava.model.Party;
import com.necpgame.backjava.model.PartyDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Party", description = "Система групп")
public interface SocialApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_PARTY = "/social/party/create";
    /**
     * POST /social/party/create : Создать группу
     * Создает новую группу. Создатель становится лидером. 
     *
     * @param createPartyRequest  (required)
     * @return Группа создана (status code 201)
     */
    @Operation(
        operationId = "createParty",
        summary = "Создать группу",
        description = "Создает новую группу. Создатель становится лидером. ",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Группа создана", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Party.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_CREATE_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Party> createParty(
        @Parameter(name = "CreatePartyRequest", description = "", required = true) @Valid @RequestBody CreatePartyRequest createPartyRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"party_id\" : \"party_id\", \"members\" : [ \"members\", \"members\" ], \"max_members\" : 0, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"leader_id\" : \"leader_id\", \"loot_mode\" : \"loot_mode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_PARTY = "/social/party/{party_id}";
    /**
     * GET /social/party/{party_id} : Получить информацию о группе
     * Возвращает детали группы, участников, настройки
     *
     * @param partyId  (required)
     * @return Информация о группе (status code 200)
     */
    @Operation(
        operationId = "getParty",
        summary = "Получить информацию о группе",
        description = "Возвращает детали группы, участников, настройки",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Информация о группе", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PartyDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SocialApi.PATH_GET_PARTY,
        produces = { "application/json" }
    )
    default ResponseEntity<PartyDetails> getParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"member_details\" : [ { \"level\" : 6, \"name\" : \"name\", \"character_id\" : \"character_id\", \"is_online\" : true, \"class\" : \"class\" }, { \"level\" : 6, \"name\" : \"name\", \"character_id\" : \"character_id\", \"is_online\" : true, \"class\" : \"class\" } ], \"party_id\" : \"party_id\", \"members\" : [ \"members\", \"members\" ], \"max_members\" : 0, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"leader_id\" : \"leader_id\", \"loot_mode\" : \"loot_mode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_INVITE_TO_PARTY = "/social/party/{party_id}/invite";
    /**
     * POST /social/party/{party_id}/invite : Пригласить в группу
     * Отправляет приглашение в группу. Только лидер может приглашать. 
     *
     * @param partyId  (required)
     * @param inviteToPartyRequest  (required)
     * @return Приглашение отправлено (status code 200)
     */
    @Operation(
        operationId = "inviteToParty",
        summary = "Пригласить в группу",
        description = "Отправляет приглашение в группу. Только лидер может приглашать. ",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Приглашение отправлено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_INVITE_TO_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> inviteToParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId,
        @Parameter(name = "InviteToPartyRequest", description = "", required = true) @Valid @RequestBody InviteToPartyRequest inviteToPartyRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_JOIN_PARTY = "/social/party/{party_id}/join";
    /**
     * POST /social/party/{party_id}/join : Присоединиться к группе
     * Принимает приглашение и присоединяется к группе
     *
     * @param partyId  (required)
     * @param joinPartyRequest  (required)
     * @return Присоединился к группе (status code 200)
     */
    @Operation(
        operationId = "joinParty",
        summary = "Присоединиться к группе",
        description = "Принимает приглашение и присоединяется к группе",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Присоединился к группе", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Party.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_JOIN_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Party> joinParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId,
        @Parameter(name = "JoinPartyRequest", description = "", required = true) @Valid @RequestBody JoinPartyRequest joinPartyRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"party_id\" : \"party_id\", \"members\" : [ \"members\", \"members\" ], \"max_members\" : 0, \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"leader_id\" : \"leader_id\", \"loot_mode\" : \"loot_mode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LEAVE_PARTY = "/social/party/{party_id}/leave";
    /**
     * POST /social/party/{party_id}/leave : Покинуть группу
     * Покидает группу. Если лидер - лидерство передается другому. 
     *
     * @param partyId  (required)
     * @param joinPartyRequest  (required)
     * @return Покинул группу (status code 200)
     */
    @Operation(
        operationId = "leaveParty",
        summary = "Покинуть группу",
        description = "Покидает группу. Если лидер - лидерство передается другому. ",
        tags = { "Party" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Покинул группу", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SocialApi.PATH_LEAVE_PARTY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> leaveParty(
        @NotNull @Parameter(name = "party_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("party_id") String partyId,
        @Parameter(name = "JoinPartyRequest", description = "", required = true) @Valid @RequestBody JoinPartyRequest joinPartyRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
