/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.necpgame.backjava.api;

import com.necpgame.backjava.model.GetNotifications200Response;
import com.necpgame.backjava.model.MarkAllNotificationsReadRequest;
import org.springframework.lang.Nullable;
import com.necpgame.backjava.model.SendNotification200Response;
import com.necpgame.backjava.model.SendNotificationRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Notifications", description = "Система уведомлений")
public interface TechnicalApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_NOTIFICATIONS = "/technical/notifications";
    /**
     * GET /technical/notifications : Получить уведомления
     * Возвращает список уведомлений. Поддерживает фильтрацию и пагинацию. 
     *
     * @param playerId  (required)
     * @param unreadOnly  (optional, default to false)
     * @param type  (optional)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 50)
     * @return Список уведомлений (status code 200)
     */
    @Operation(
        operationId = "getNotifications",
        summary = "Получить уведомления",
        description = "Возвращает список уведомлений. Поддерживает фильтрацию и пагинацию. ",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Список уведомлений", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetNotifications200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TechnicalApi.PATH_GET_NOTIFICATIONS,
        produces = { "application/json" }
    )
    default ResponseEntity<GetNotifications200Response> getNotifications(
        @NotNull @Parameter(name = "player_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "player_id", required = true) String playerId,
        @Parameter(name = "unread_only", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "unread_only", required = false, defaultValue = "false") Boolean unreadOnly,
        @Parameter(name = "type", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "type", required = false) @Nullable String type,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "50") Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"pagination\" : { \"total\" : 156, \"has_next\" : true, \"page\" : 1, \"total_pages\" : 8, \"has_prev\" : false, \"page_size\" : 20 }, \"notifications\" : [ { \"is_read\" : true, \"player_id\" : \"player_id\", \"data\" : \"{}\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"notification_id\" : \"notification_id\", \"type\" : \"system\", \"priority\" : \"low\", \"message\" : \"message\" }, { \"is_read\" : true, \"player_id\" : \"player_id\", \"data\" : \"{}\", \"created_at\" : \"2000-01-23T04:56:07.000+00:00\", \"notification_id\" : \"notification_id\", \"type\" : \"system\", \"priority\" : \"low\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_MARK_ALL_NOTIFICATIONS_READ = "/technical/notifications/mark-all-read";
    /**
     * POST /technical/notifications/mark-all-read : Отметить все как прочитанные
     * Отмечает все уведомления как прочитанные
     *
     * @param markAllNotificationsReadRequest  (required)
     * @return Все уведомления прочитаны (status code 200)
     */
    @Operation(
        operationId = "markAllNotificationsRead",
        summary = "Отметить все как прочитанные",
        description = "Отмечает все уведомления как прочитанные",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Все уведомления прочитаны", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_MARK_ALL_NOTIFICATIONS_READ,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> markAllNotificationsRead(
        @Parameter(name = "MarkAllNotificationsReadRequest", description = "", required = true) @Valid @RequestBody MarkAllNotificationsReadRequest markAllNotificationsReadRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_MARK_NOTIFICATION_READ = "/technical/notifications/{notification_id}/mark-read";
    /**
     * POST /technical/notifications/{notification_id}/mark-read : Отметить как прочитанное
     * Отмечает уведомление как прочитанное
     *
     * @param notificationId  (required)
     * @return Уведомление прочитано (status code 200)
     */
    @Operation(
        operationId = "markNotificationRead",
        summary = "Отметить как прочитанное",
        description = "Отмечает уведомление как прочитанное",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Уведомление прочитано", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_MARK_NOTIFICATION_READ,
        produces = { "application/json" }
    )
    default ResponseEntity<Object> markNotificationRead(
        @NotNull @Parameter(name = "notification_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("notification_id") String notificationId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SEND_NOTIFICATION = "/technical/notifications/send";
    /**
     * POST /technical/notifications/send : Отправить уведомление
     * Отправляет уведомление игроку. Используется системой для различных событий. 
     *
     * @param sendNotificationRequest  (required)
     * @return Уведомление отправлено (status code 200)
     */
    @Operation(
        operationId = "sendNotification",
        summary = "Отправить уведомление",
        description = "Отправляет уведомление игроку. Используется системой для различных событий. ",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Уведомление отправлено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SendNotification200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TechnicalApi.PATH_SEND_NOTIFICATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SendNotification200Response> sendNotification(
        @Parameter(name = "SendNotificationRequest", description = "", required = true) @Valid @RequestBody SendNotificationRequest sendNotificationRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notification_id\" : \"notification_id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
